
name: dduffey-smartcon
version: "1.0"
summary: DDuffey's Smart Air Conditioning
description: This will turn on the systems fan when the temperature difference between active/occupied rooms is large.
confinement: strict
